#
# This source file is part of the HealthKitOnOMH open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test-spm:
    name: Build and Test Swift Package
    uses: StanfordBDHG/.github/.github/workflows/build-and-test-xcodebuild-spm.yml@v1
    with:
      scheme: HealthKitOnOMH-Package
  create-and-upload-coverage-report:
    name: Create and Upload Coverage Report
    needs: build_and_test-spm
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - uses: actions/download-artifact@v3
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        xcode: true
        xcode_archive_path: HealthKitOnOMH-Package.xcresult
