#
# This source file is part of the HealthKitOnOMH open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test-spm:
    name: Build and Test Swift Package
    uses: StanfordBDHG/.github/.github/workflows/build-and-test-xcodebuild-spm.yml@v1
    with:
      scheme: HealthKitOnOMH-Package
  build_and_test-uitests:
    name: Build and Test UITest App
    uses: StanfordBDHG/.github/.github/workflows/build-and-test-xcodebuild.yml@v1
    with:
      xcodeprojname: Tests/UITests/UITests.xcodeproj
      scheme: TestApp
